#!/bin/sh

pip install -i https://test.pypi.org/simple/ slidesave

EXE_PATH=`which slidesave_cli`
echo $EXE_PATH


APP_DIR="$HOME/.local/share/applications"
APP_PATH="$APP_DIR""/slidesave.desktop"
IMG_DIR="$HOME""/slidesave"
IMG_PATH="$IMG_DIR""/icon.png"

if [ ! -d $APP_DIR ]; then
    mkdir -p $APP_DIR
fi
if [ ! -d $IMG_DIR ]; then
    mkdir -p $IMG_DIR
fi

if [ ! -f $IMG_PATH ]; then
    curl -o $IMG_PATH "https://github.com/subrat-lima/slidesave/blob/main/icon.png"
fi

echo "[Desktop Entry]" > $APP_PATH
echo "Encoding=UTF-8" >> $APP_PATH
echo "Version=0.0.2" >> $APP_PATH
echo "Type=Application" >> $APP_PATH
echo "Terminal=False" >> $APP_PATH
echo "Exec=$APP_PATH" >> $APP_PATH
echo "Name=slideshare" >> $APP_PATH
echo "Icon=$IMG_PATH" >> $APP_PATH

echo "desktop entry added for slidesave"
