#!/bin/sh

# urls
IMG_URL="https://github.com/subrat-lima/slidesave/blob/main/icon.png"
TEST_PYPI_URL="https://test.pypi.org/simple/"
PROD_PYPI_URL="https://pypi.org/simple/"

# directories
APP_DIR="$HOME/.local/share/applications"
APP_PATH="$APP_DIR/slidesave.desktop"
DATA_DIR="$HOME/slidesave"
IMG_PATH="$DATA_DIR/icon.png"
EXE_PATH=`which slidesave_cli`

# uninstall slidesave
pip uninstall slidesave -y

# need to have pip installed and configured for this installation to work
pip install -i $TEST_PYPI_URL --extra-index-url $PROD_PYPI_URL slidesave

# create $APP_DIR if not exists
if [ ! -d $APP_DIR ]; then
    mkdir -p $APP_DIR
fi

# create $DATA_DIR if not exists
if [ ! -d $DATA_DIR ]; then
    mkdir -p $DATA_DIR
fi

# download icon if not exists
if [ ! -f $IMG_PATH ]; then
    curl -o $IMG_PATH $IMG_URL
fi

append()
{
    echo $1 >> $APP_PATH
}

echo -n > $APP_PATH
append "[Desktop Entry]"
append "Encoding=UTF-8"
append "Version=0.0.5"
append "Type=Application"
append "Terminal=False"
append "Exec=$EXE_PATH"
append "Name=slidesave"
append "Icon=$IMG_PATH"

echo "desktop entry added for slidesave at " $APP_PATH
